language: java

jdk:
  - oraclejdk10
  - oraclejdk9
  - oraclejdk8
  - openjdk10
  - openjdk9
  - openjdk8


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew --daemon
  - ./gradlew assemble
  - ./gradlew test
#  TODO: store linux version of libirohajava in ${jniDir} and then uncomment it
#  - ./gradlew integration
  - ./gradlew javadoc
